[package]
name = "egg-smol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1"
indexmap = "1.8"
hashbrown = "0.12"
ahash = { version = "0.7", default-features = false } 
