[package]
name = "egg-smol"
version = "0.1.0"
edition = "2021"

[workspace]

members = [
    ".",
    "web-demo",
]

[dependencies]
thiserror = "1"
once_cell = "1"
indexmap = "1.8"
hashbrown = "0.12"
log = "0.4"
ahash = { version = "0.7", default-features = false }

lalrpop-util = { version = "0.19.7", features = ["lexer"] }
regex = "1"

[dev-dependencies]
env_logger = "0.9"

[build-dependencies]
lalrpop = "0.19.7"

# pest = "2.1"
# pest_derive = "2.1"

# logos = "0.12"
